import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
import { TaskInput, TaskNoteInput } from '../components/TaskInput'
import ItemList from '../components/ItemList'
import { useState } from 'react'

export default function Home() {
  const [tasks, setTasks] = useState([])

  async function createTask(e) {
      e.preventDefault()

      const task = {
          name: e.target[0].value,
          note: e.target[1].value
      }
      
      e.target.reset();

      // Here the amplify code ...
      setTasks([...tasks, task])
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h6 className={styles.title}>
        Welcome to Glorified TodoList!
        </h6>

        <p className={styles.description}>
          Smart way to think about your tasks
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <form onSubmit={createTask}>
              <TaskInput />
              <TaskNoteInput />
              <Button label="Crear" small/>
            </form>
          </div>

          <div className={styles.card}>
            <ItemList tasks={tasks}/>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a className={styles.signingout}>Sign out</a>
      </footer>
    </div>
  )
}