import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import { TaskInput, TaskNoteInput } from "../components/TaskInput";
import ItemList from "../components/ItemList";
import { useState, useEffect } from "react";
import { Auth, graphqlOperation, API, Predictions } from "aws-amplify";
import { useRouter } from "next/router";
import { createTodo } from "../src/graphql/mutations";
import { listTodos } from "../src/graphql/queries";

export default function Home() {
  const router = useRouter();
  const [tasks, setTasks] = useState([]);
  const [user, setUser] = useState(null);

  async function getTasks() {
    if (!user) return;

    const serverTasks = await API.graphql({ query: listTodos });

    setTasks([...serverTasks.data.listTodos.items]);
  }

  const signOut = () => {
    Auth.signOut()
      .then(() => {
        setUser(null);
        router.push("/signin");
      })
      .catch(() => {
        console.error("Error trying to signout");
      });
  };

  useEffect(() => {
    getTasks();
  });

  useEffect(() => {
    Auth.currentAuthenticatedUser()
      .then((user) => {
        console.log(`User logged: ${JSON.stringify(user)}`);
        setUser(user);
      })
      .catch(() => {
        setUser(null);
        router.push("/signin");
      });
  }, []);

  async function createTask(e) {
    e.preventDefault();

    const task = {
      name: e.target[0].value,
      note: e.target[1].value,
    };

    e.target.reset();

    try {
      const newCreatedTask = await API.graphql(
        graphqlOperation(createTodo, { input: task })
      );

      if (newCreatedTask) {
        console.log(
          `Task created ${JSON.stringify(newCreatedTask.data.createTodo)}`
        );
        setTasks([...tasks, newCreatedTask.data.createTodo]);

        Predictions.interpret({
          text: {
            source: {
              text: newCreatedTask.data.createTodo.note,
            },
            type: "ALL",
          },
        })
          .then((result) => console.log(result))
          .catch((error) => console.error(error));
      }
    } catch (error) {
      console.error("Error creating the tasks " + error.message);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Glorified TodoList!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h6 className={styles.title}>
          {user ? `Welcome ${user.username}` : "Welcome"} to Glorified TodoList!
        </h6>

        <p className={styles.description}>
          Smart way to think about your tasks
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <form onSubmit={createTask}>
              <TaskInput />
              <TaskNoteInput />
              <Button label="Crear" small />
            </form>
          </div>

          <div className={styles.card}>
            <ItemList tasks={tasks} />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a className={styles.signingout} onClick={signOut}>
          Sign out
        </a>
      </footer>
    </div>
  );
}
